
call plug#begin('~/.vim/plugged')

" Plug 'https://github.com/vim-scripts/matchit.zip'
  Plug 'https://github.com/JalaiAmitahl/maven-compiler.vim'
  Plug 'https://github.com/junegunn/vim-easy-align'
" Plug 'https://github.com/pangloss/vim-javascript'
" Plug 'https://github.com/othree/yajs.vim'
" Plug 'https://github.com/jelera/vim-javascript-syntax.git'
  Plug 'https://github.com/othree/javascript-libraries-syntax.vim'
  Plug 'https://github.com/mxw/vim-jsx.git'
" Plug 'https://github.com/udalov/kotlin-vim'
" Plug 'https://github.com/vim-scripts/dbext.vim'
" Plug 'https://github.com/cosminadrianpopescu/vim-sql-workbench'
  Plug 'https://github.com/preservim/tagbar.git'
  Plug 'https://github.com/xolox/vim-easytags'
  Plug 'https://github.com/xolox/vim-misc'
  Plug 'https://github.com/tpope/vim-fugitive.git'
  Plug 'https://github.com/tpope/vim-scriptease.git'
  Plug 'https://github.com/junegunn/gv.vim.git'
  Plug 'junegunn/fzf'
  Plug 'junegunn/fzf.vim'
" Plug 'https://github.com/scrooloose/syntastic'
  Plug 'https://github.com/cespare/vim-toml'
  Plug 'https://github.com/tmux-plugins/vim-tmux'
" Plug 'https://github.com/tomtom/brep_vim'
  Plug 'https://github.com/vim-scripts/GrepCommands.git'
  Plug 'https://github.com/vim-scripts/GrepHere.git'
  Plug 'https://github.com/vim-airline/vim-airline'
  Plug 'https://github.com/vim-airline/vim-airline-themes'
  Plug 'https://github.com/mildred/vim-bufmru.git'
  Plug 'https://github.com/edkolev/tmuxline.vim'
" Plug 'https://github.com/chrisbra/changesPlugin.git'
  Plug 'https://github.com/edkolev/promptline.vim'
  Plug 'https://github.com/vim-scripts/python_match.vim.git'
  Plug 'https://github.com/neomake/neomake'
  Plug 'https://github.com/vim-scripts/CmdlineComplete.git'
  Plug 'https://github.com/artur-shaik/vim-javacomplete2.git'
" Plug 'https://github.com/codeindulgence/vim-tig'
  Plug 'https://github.com/rhysd/devdocs.vim.git'
  Plug 'https://github.com/elzr/vim-json.git'
  Plug 'https://github.com/themadsens/jcall.vim.git'
  Plug 'https://github.com/tomtom/quickfixsigns_vim.git'
  Plug 'https://github.com/ctrlpvim/ctrlp.vim.git'
" Plug 'https://github.com/ternjs/tern_for_vim'
  Plug 'https://github.com/sjl/vitality.vim'
" Plug 'https://github.com/zerowidth/vim-copy-as-rtf'
" Plug 'https://github.com/natebosch/vim-lsc'
" Plug 'https://github.com/themadsens/VimPyServer'
  Plug 'https://github.com/rust-lang/rust.vim'
  Plug 'https://github.com/preservim/nerdtree.git'
  Plug 'ziglang/zig.vim'
  Plug 'simnalamburt/vim-mundo'
  Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && yarn install'  }
  Plug 'kdheepak/lazygit.nvim'
  Plug 'mhinz/vim-signify'
  Plug 'ryanoasis/vim-devicons'
" Plug 'kyazdani42/nvim-web-devicons'
  Plug 'kergoth/vim-bitbake'
  Plug 'Vimjas/vim-python-pep8-indent'
if 0 && has('nvim')
  Plug 'andymass/vim-matchup'
  Plug 'nvim-treesitter/nvim-treesitter'
endif


call plug#end()

