#!/bin/bash
LUADIR=${LUA_CPATH%/?.so}
LUADIR=${LUADIR##*;}
AGENTDIR=${LUADIR%/lua}
export LD_LIBRARY_PATH AMP_LUA_CPATH
if [[ $(file ${LUADIR}/amplua.so) != *80386* ]] ;then
    LUA_CPATH=';;/opt/toolchain/X86/usr/lib/lua/5.1/?.so'
fi
for d in $AGENTDIR/libs/*/*.so ;do
    LD_LIBRARY_PATH=${d%/*.so}:$LD_LIBRARY_PATH
done
#env | grep LUA
case ${0##*/} in
	xmltool) exec $AGENTDIR/libs/scripts/xmltool "$@" ;;
	damdecode) exec $AGENTDIR/libs/scripts/damdecode "$@" ;;
	xmlacsend) exec $AGENTDIR/messageswitch/xmlacsend/xmlacsend "$@" ;;
    runlua) exec "$@" ;;
esac
echo "No such alias (yet)"
exit 1
